apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service-connectivity-server
  labels:
    app: service-connectivity-server
    sample: service-connectivity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-connectivity-server
  template:
    metadata:
      labels:
        app: service-connectivity-server
        sample: service-connectivity
    spec:
      containers:
        - name: server
          image: nginx:alpine

---
apiVersion: v1
kind: Service
metadata:
  name: service-connectivity-service
  labels:
    sample: service-connectivity
spec:
  selector:
    app: service-connectivity-server
    sample: service-connectivity
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service-connectivity-client
  labels:
    app: service-connectivity-client
    sample: service-connectivity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-connectivity-client
  template:
    metadata:
      labels:
        app: service-connectivity-client
        sample: service-connectivity
    spec:
      containers:
        - name: client
          image: rajchaudhuri/service-connectivity-tester:alpine
          env:
            - name: SERVICE_URL
              value: "http://service-connectivity-service"
